default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: volt_development

test:
  <<: *default
  database: volt_test

production:
  <<: *default
  database: <%= ENV['VOLT_DATABASE_NAME'] %>
  username: <%= ENV['VOLT_DATABASE_USERNAME'] %>
  password: <%= ENV['VOLT_DATABASE_PASSWORD'] %>
