default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_expiration_hours: 6
  jwt_secret_key: <%= ENV['JWT_SECRET_KEY'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
